### ISSUE TITLE
Get MathJax to work offline somehow

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/arcade-mode#7]

**Comment by timolawl** [comment]
Importing MathJax into our React codebase caused errors because MathJax 2.x is currently incompatible with strict mode code that our React/Redux codebase runs in. The solution was simply to reference it outside of the strict mode code as a local file. We now have it imported on the page via a script tag: `<script src="public/js/MathJax.min.js?config=TeX-AMS_SVG"></script>`.

I was able to use a compiled version that sits at 1.3M minified. Our app is once again completely offline compliant.

Commits:
https://github.com/freeCodeCamp/arcade-mode/commit/62c6d15c3b2549fdc08029dbe68ea7a5d008cea6
https://github.com/freeCodeCamp/arcade-mode/commit/6921ef6c5ae03bd17878d86cb3ddb7564c034905
https://github.com/freeCodeCamp/arcade-mode/commit/c3ee6b63f37fd486d5c46fde6867b60ffdfad0b6

https://github.com/freeCodeCamp/arcade-mode/commit/b7fc58035faf7d98faee1eb391e1ad04b1d3c450
https://github.com/freeCodeCamp/arcade-mode/commit/f562cdfa423afcf905dac36b4c6c5ed4e006ba6f

**Comment by QuincyLarson** [comment]
@timolawl Awesome news! Thanks for getting to the bottom of this, and updating us!
